### ISSUE TITLE
Quest ratings + reviews

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#248]
V1 DONE: gather data from users, store internally
- In May, delete old /feedback route

**Design doc for v2: expose as part of searching / sorting**

UI: As part of searching and filtering:
- display each quest's family-friendly tag, average rating (in stars) and number of ratings (numerical) as part of result element (see Amazon for inspiration)
  - perhaps use chip components (or something similar, but more Expedition-y) plus icons to make it easy + compact to see this info: http://www.material-ui.com/#/components/chip
  - perhaps only show info that's not filtered on? IE if you're filtering by current number of adventurers, you don't need to see that a quest supports 3-5....
- filtering
  - to the top: sort: newest (default), highest rated (all time), highest rated (this month) (aka highest rated quests that were published in the last month), alphabetical
  - to the bottom: star-based filter, only show quests N stars and up (1-4)

*Idea dump for future versions:*

- editing reviews on replay - if they've already written a review for a quest, pre-populate their old answer
- listing rating / reviews you've submitted
  - ability to edit them
    - email to QC should be slightly different, user updated their review
  - possibly also listing all quests you've played, though we'll also have to start tracking that

**Comment by toddmedema** [comment]
Researched options. Boils down to if we code it ourselves or use an external API.

Either way, we'll need a UI for selecting # of stars. Something like this would work nicely: https://github.com/djchie/react-native-star-rating

Code it ourselves: UI, transmit to API, (endpoints <> DB), get results from API

API: UI, transmit to API, get results from API

- couldn't find any APIs just for posted and getting reviews and comments to and from
- but, did find some interesting options for recommendation engines
  - https://www.recombee.com/
  - https://aws.amazon.com/machine-learning/
  - https://cloud.google.com/prediction/docs/quickstart
  - https://www.microsoft.com/cognitive-services/en-us/recommendations/documentation

**Comment by toddmedema** [comment]
@smartin015 updated the first comment to be the design doc discussed. LMK what you think!

**Comment by smartin015** [comment]
Maturity level... might be easier/less mental overhead to just have a "flag as mature" feedback button for quests the author marks as PG/PG13 but which have stuff that's more graphic than the rating they gave. This way, users have less work to do and the rating system is still enforced.

Not already mentioned, but I assume there's a query to fetch and account for past ratings when recalculating the aggregate scores when the same user rates a second time?

We should probably make the new rating process not inline, i.e. UI shouldn't be held up because we're doing a table scan to sum up and recalculate ratings on a quest they've just finished playing.

I'd also suggest adding a "visible" field to the rating table to allow us to moderate/shadowban users quickly if necessary, along with perhaps a "blacklist" table the ratings system can reference and we can manually enter data for that sets this field for new reviews by a user. If we can code it now, we won't need to when we have to move quickly.

In the future, could we have design docs be actual google docs? It's hard to track comments and updates in a github issue.

**Comment by toddmedema** [comment]
1) hmm. I think having the quest author provide a rating would make sense. That's how the Android marketplace does it - the app author inputs ratings on things like "does this app reference alcohol?" "does it depict violence? no / comic / realistic", etc, and then using that to automatically calculate a rating. Which would make more sense than asking using to assign an overall rating...

2) ratings are unique per quest and user, so a second rating from the same user would override the first. Have it on the "future" list to let users edit their existing ratings / have their previous rating pre-populate the rating box

3) I don't think it is? Pretty sure the recalculation stuff happens after the response is ended

4 + 5) good ideas

TODO:
- move quest rating itself to QC side of things
  - question: how to handle existing quests? unrated until authors re-publish?
  - on quest publish, ask authors a series of questions (based on Android market questions; store the answer to each question then calculated result)
- in the user rating screen, state "the quest author rated this as appropriate for ages X+ <flag as inappropriate> -> emails us"
- add "visible" boolean columns to ratings
  - future: add app users table, with "visible" column for shadow banning

**Comment by toddmedema** [comment]
@smartin015 LMK if that sounds good or if you have any other input :)

**Comment by smartin015** [comment]
I think for simplicity, we should just include a rating field attribute on the quest. The question-based workflow would be nice, but would definitely add more cruft to the UI. Other than that, LGTM

**Comment by toddmedema** [comment]
Duplicate of https://github.com/ExpeditionRPG/expedition-app/issues/327
