### ISSUE TITLE
Inform user on bogus quest load

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#331]
We should appropriately handle malformed XML/QDL on load.

It'd be nice to also have a unit test - e.g. fake web response with bogus XML, to ensure we surface some error.

**Comment by toddmedema** [comment]
Implementation note: Cheerio doesn't throw an error if you pass it invalid XML, so we can probably skip straight to checking if the XML has a quest structure (since invalid XML returns an empty Cheerio document).

MVP check could be to just confirm that the root node is a quest, and that there's only one root node

**Comment by smartin015** [comment]
Closing as dupe of #154
