### ISSUE TITLE
Full-width [art]

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#403]
Now: support the display of full-width images, which will be put into the QC as [art] and likely render as an IMG tag. Pairs with: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/349

Roll out:
- DONE: Deploy app support for ::. #Edge case to check: instruction icons
- DONE: Deploy QC support for :: & updating starting quest and docs
- DONE: Publish in blog update + add [icon] deprecation warning
- DONE: Two+ weeks later: Deploy QC update that throws error on [icon] usage, Update all existing / published quests - re-publish, make sure ::'s are working fine for them
- DONE: App: switch [] to be full-width art: https://github.com/ExpeditionRPG/expedition-app/pull/505
- DONE: Update QC docs: include demo of [art] and [art_full] in docs - https://github.com/ExpeditionRPG/expedition-quest-creator/pull/425
- DONE: Update QDL to not throw error 435 if it's a roleplaying line whose sole text is [art] (otherwise, change the error to be "[art] should be on it's own line. You can also add _full to the art name to make it full width. Or, you can change it to :icon: for a smaller icon that's inline with the text" - https://github.com/ExpeditionRPG/expedition-qdl/pull/32

Previously:
* Underscore text isn't italicized in RP cards
* After Surge - rename "killed" to "knocked out" or similar
* Add logic for singular vs plural noun for draw enemy/enemies card
* Step 1 of quest setup - mention you can select whichever adventurer you want

**Comment by toddmedema** [comment]
Closed everything except the first with https://github.com/ExpeditionRPG/expedition-app/commit/1b961e87e06032e975db9b63ad5127d760331c7e

Looks like both `_` and `*` are supported for markdown emphasis, though support for that would belong in the QC / Markdown -> XML renderer, yes?
 https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf

In reviewing their syntax guide, two other thoughts:
- Should we add support for headers via # / ## / ###? Maybe not, since pages already have titles and we don't really want to encourage a single page to be long enough to need headers....
- What if we used `:icon:` for icon support / deprecated the `[icon]` format? Seems to be how Markdown, Slack, etc use it... we could then, in the future, use `[]`'s for something else, like full-width art?

**Comment by smartin015** [comment]
Yep, we'd need to add support into the renderer code to turn it into html tags.

* Agreed, no headers for now.
* Makes sense, and large images could use the typical `![]()` format.

**Comment by toddmedema** [comment]
Remainder of issue is tagged for October now that the initial support for `:icons:` is released

**Comment by toddmedema** [comment]
Quest migration to `:icon:` notes:

ERRORS
Stormin' the Castle & Legend of the Mystics -> Errors caught in playtest.js aren't displayed + don't stop "validating..." (once fixed, correct this test and re-publish)
When the King is Away, Bridezilla... no access?
-> Spellcheck is still flagging things inside of **goto xxx**s (seen in Staircase)

DONE
Survival
An Expedition to the Past
Dread Apprentice 1
Actual Cannibal
Fishin' With Dad
Escape from Fallhaven
Z.E. #1
Bear Hunt
Staircase
Weird Encounter
LC#1
LC#2
LC#3
LC#4
LC#5
WB#1
WB#2
Who will you be?
Staff of Worldly-Might
Dark Castle
