### ISSUE TITLE
Allow quests to skip the intro/setup card

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#428]
Future quests (such as the one by Louise and Earl) will have specific instructions on how to set up the game - drawing specific adventurers, abilities, loot, and/or persona cards. Without skipping the initial instruction card, adventurers would end up doing unnecessary extra setup work.

One way to do this would be to have something like `<quest skipSetup="true">` which just spits the user out into the main storyline. The quest creator can add a few initial cards of setup at their discretion.

**Comment by toddmedema** [comment]
Since the QC works in markdown instead of XML, perhaps this returns to that previous metadata implementation we had, where it's fields below the title?
```
_Title of quest_
skipSetup: true
```

Or even just for boolean flags that default to no:
```
_Title of quest_
skipSetup
```

Something to consider here is how we'd want to do other types of metadata in the future, such as (listing required media files?)... though, looking through our backlog, I can't really find any other metadata things to consider...


Another idea: What if it was an ops function, and we added the ability to call ops functions as soon as the quest started / before even the setup card was shown?

**Comment by smartin015** [comment]
Perhaps. I'm more amenable to just using JSON for now, since this will probably not be a common feature and that sort of metadata implementation will take significantly more work.

**Comment by toddmedema** [comment]
So, `_Title of quest_ {skipSetup: true}`? That seems reasonable, since it's a pretty advanced feature
