### ISSUE TITLE
Quest Fixes From Feedback

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#434]
Oust Albanus: "Lost the battle to win by making a decision without another battle? The Win felt hollow and cheap."

Actual Cannibal Shia Labeouf: "Shia should have a special ability, and he didn't have a tier in the second encounter."

Going on a Bear Hunt: "We called off the hunt from the cave to deliver the druids message and "Cowards Choice" described "a fight lost" and druid nursing us back to health--that never happened to us. Mistaken code path that should be an easy fix."

**Comment by toddmedema** [comment]
Oust: Added combat after tossing the powder keg into the fire so that you can't accidentally skip the boss fight: https://github.com/ExpeditionRPG/expedition-app/commit/a812f44a83701c072a3da7727c7067fc388dbdf1

Shia LaBeouf: Fixed, the bug was that `{{!bodySlam}}` doesn't actually detect if bodySlam is false / doesn't exist. You have to make sure you define it to false all the time, and then explicitly check for `{{bodySlam == false}}`

Going on a Bear Hunt: sent feedback to Katie
