### ISSUE TITLE
Dungeon Crawl Mode

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#55]
Successively tougher tiers, in a survival style. Maybe have a difficulty selector so there's 4-5 rounds of a given tier per crawl

Could also have two modes: endless / see how long you can survive, and ~fixed length, ie we have 30 minutes to play, and it ramps up the difficulty based on that timeframe (ie 30 minutes = 3 encounters, so easy fight, then medium fight, then hard fight)

Should name the tier to draw, like the loot system: Draw 2 Tier III enemies, Draw 1 Tier I enemy.

**Comment by toddmedema** [comment]
Idea: instead of this /just/ being combat, could turn it into a sort of auto-generated quest system. At the very least, intersperse a roleplaying card or two between combat with randomly generated text like "The dungeon grows damper as you descend the ancient stone staircase, your torches flickering in a gust of wind from below."

**Comment by toddmedema** [comment]
First challenge: figuring out the random enemy syntax: https://github.com/Fabricate-IO/expedition-quest-creator/issues/196
